#*****************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# axi_fft.tcl: Tcl script for re-creating project 'axi_fft'
#
# Generated by Vivado on Fri Aug 25 15:34:49 +0800 2023
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (axi_fft.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/ip/data_buffer/data_buffer.xci"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/xfft_gen_r5.edif"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/ddc5_f1_v01010200/ddc5_f1_v0101.edif"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/ddc5_f1_v01010200/pfir_coef_reload.edif"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/ddc5_f1_v01010200/ddc5_f1_v0101.v"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/ddc5_f1_v01010200/ddc5_f1_v0101_top.v"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/ddc5_f1_v01010200/pfir_coef_reload.v"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/xfft_gen_r5.v"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/xfft_convert.sv"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/src/axi_fft.sv"
#    "D:/Work/825/vsat-fpga-develop/library/rz/axi_fft/axi_fft/axi_fft.srcs/sources_1/imports/axi_fft/component.xml"
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/Work/825/vsat-fpga-develop/library/rz/com/axi_if/s_axi_lite_reg.v"
#
#*****************************************************************************************



# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "${origin_dir}/../com/axi_if/s_axi_lite_reg.sv"\
 "[file normalize "$origin_dir/src/axi_spi_master_ctrl.sv"]"\
 "[file normalize "$origin_dir/src/axi_spi_master.v"]"\
 "[file normalize "$origin_dir/src/spi_master_ctrl.sv"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/../com/axi_if/s_axi_lite_reg.sv"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "axi_spi_master"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "axi_spi_master.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/axi_fft"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z100ffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z100ffg900-2" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "2" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "2" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "2" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "2" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "2" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "2" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}


set src_dir [pwd]

set axi_reg "${origin_dir}/../com/axi_if/s_axi_lite_reg.sv"


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../com/axi_if/s_axi_lite_reg.sv"] \
]
add_files -norecurse -fileset $obj $files



set obj [get_filesets sources_1]
set files [list \
 [file normalize "${src_dir}/src/axi_spi_master_ctrl.sv"] \
]
add_files -norecurse -fileset $obj $files



set obj [get_filesets sources_1]
set files [list \
 [file normalize "${src_dir}/src/axi_spi_master.sv"] \
]
add_files -norecurse -fileset $obj $files


set obj [get_filesets sources_1]
set files [list \
 [file normalize "${src_dir}/src/spi_master_ctrl.sv"] \
]
add_files -norecurse -fileset $obj $files


set_property top $_xil_proj_name_  [current_fileset]




ipx::package_project -root_dir $src_dir -vendor vrhacker.com -library user -taxonomy /UserIP -import_files -set_current false -force

ipx::open_ipxact_file "${src_dir}/component.xml"

#移除本地文件目录的s_axi_lite_reg
ipx::remove_file src/s_axi_lite_reg.sv [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
#移除本地文件目录的s_axi_lite_reg
ipx::add_file $axi_reg [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]
set_property type systemVerilogSource [ipx::get_files ../com/axi_if/s_axi_lite_reg.sv -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]
set_property library_name xil_defaultlib [ipx::get_files ../com/axi_if/s_axi_lite_reg.sv -of_objects [ipx::get_file_groups xilinx_anylanguagesynthesis -of_objects [ipx::current_core]]]

ipx::merge_project_changes files [ipx::current_core]


ipx::remove_user_parameter C_S00_AXI_DATA_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_S00_AXI_ADDR_WIDTH [ipx::current_core]

ipx::associate_bus_interfaces -busif s00_axi -clock s00_axi_aclk [ipx::current_core]

ipx::remove_bus_interface spi_clk [ipx::current_core]

set_property range 4096 [ipx::get_address_blocks reg0 -of_objects [ipx::get_memory_maps s00_axi -of_objects [ipx::current_core]]]



ipx::merge_project_changes ports [ipx::current_core]


set_property core_revision 2 [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::check_integrity [ipx::current_core]

ipx::save_core [ipx::current_core]

####删除原工程


if { $DEL_PROJ == 1} {
	close_project

	file delete -force $_xil_proj_name_
}

