set_property PACKAGE_PIN B10 [get_ports {GPIO_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_o[0]}]

set_property PACKAGE_PIN C10 [get_ports LOS]
set_property IOSTANDARD LVCMOS33 [get_ports LOS]

set_property PACKAGE_PIN AJ16 [get_ports ddr_clk_clk_p]
set_property IOSTANDARD LVDS [get_ports ddr_clk_clk_p]
set_property IOSTANDARD LVDS [get_ports ddr_clk_clk_n]

set_property PACKAGE_PIN A12 [get_ports {GPIO_1_tri_io[0]}]
set_property PACKAGE_PIN B12 [get_ports {GPIO_1_tri_io[1]}]
set_property PACKAGE_PIN C13 [get_ports {GPIO_1_tri_io[2]}]
set_property PACKAGE_PIN A13 [get_ports {GPIO_1_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_1_tri_io[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_1_tri_io[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_1_tri_io[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_1_tri_io[0]}]

set_property PACKAGE_PIN AF14 [get_ports {C0_DDR4_adr[0]}]
set_property PACKAGE_PIN AK15 [get_ports {C0_DDR4_adr[1]}]
set_property PACKAGE_PIN AM16 [get_ports {C0_DDR4_adr[2]}]
set_property PACKAGE_PIN AK14 [get_ports {C0_DDR4_adr[3]}]
set_property PACKAGE_PIN AF18 [get_ports {C0_DDR4_adr[4]}]
set_property PACKAGE_PIN AF16 [get_ports {C0_DDR4_adr[6]}]
set_property PACKAGE_PIN AM15 [get_ports {C0_DDR4_adr[7]}]
set_property PACKAGE_PIN AL17 [get_ports {C0_DDR4_adr[8]}]
set_property PACKAGE_PIN AM17 [get_ports {C0_DDR4_adr[9]}]
set_property PACKAGE_PIN AN17 [get_ports {C0_DDR4_adr[5]}]
set_property PACKAGE_PIN AJ13 [get_ports {C0_DDR4_adr[10]}]
set_property PACKAGE_PIN AK18 [get_ports {C0_DDR4_adr[11]}]
set_property PACKAGE_PIN AP15 [get_ports {C0_DDR4_adr[12]}]
set_property PACKAGE_PIN AN18 [get_ports {C0_DDR4_adr[13]}]
set_property PACKAGE_PIN AH14 [get_ports {C0_DDR4_adr[14]}]
set_property PACKAGE_PIN AN14 [get_ports {C0_DDR4_adr[15]}]
set_property PACKAGE_PIN AN15 [get_ports {C0_DDR4_adr[16]}]
set_property PACKAGE_PIN AF13 [get_ports {C0_DDR4_ba[0]}]
set_property PACKAGE_PIN AP16 [get_ports {C0_DDR4_ba[1]}]
set_property PACKAGE_PIN AG14 [get_ports {C0_DDR4_bg[0]}]
set_property PACKAGE_PIN AH18 [get_ports {C0_DDR4_ck_t[0]}]
set_property PACKAGE_PIN AJ17 [get_ports {C0_DDR4_cke[0]}]
set_property PACKAGE_PIN AM14 [get_ports {C0_DDR4_cs_n[0]}]
set_property PACKAGE_PIN AP13 [get_ports {C0_DDR4_dm_n[0]}]
set_property PACKAGE_PIN AL9 [get_ports {C0_DDR4_dm_n[1]}]
set_property PACKAGE_PIN AG12 [get_ports {C0_DDR4_dm_n[2]}]
set_property PACKAGE_PIN AP8 [get_ports {C0_DDR4_dm_n[3]}]
set_property PACKAGE_PIN AN8 [get_ports {C0_DDR4_dq[0]}]
set_property PACKAGE_PIN AN12 [get_ports {C0_DDR4_dq[1]}]
set_property PACKAGE_PIN AN10 [get_ports {C0_DDR4_dq[2]}]
set_property PACKAGE_PIN AP12 [get_ports {C0_DDR4_dq[3]}]
set_property PACKAGE_PIN AN7 [get_ports {C0_DDR4_dq[4]}]
set_property PACKAGE_PIN AN13 [get_ports {C0_DDR4_dq[5]}]
set_property PACKAGE_PIN AP11 [get_ports {C0_DDR4_dq[6]}]
set_property PACKAGE_PIN AP10 [get_ports {C0_DDR4_dq[7]}]
set_property PACKAGE_PIN AK9 [get_ports {C0_DDR4_dq[8]}]
set_property PACKAGE_PIN AM12 [get_ports {C0_DDR4_dq[9]}]
set_property PACKAGE_PIN AK10 [get_ports {C0_DDR4_dq[10]}]
set_property PACKAGE_PIN AM11 [get_ports {C0_DDR4_dq[11]}]
set_property PACKAGE_PIN AM9 [get_ports {C0_DDR4_dq[12]}]
set_property PACKAGE_PIN AL13 [get_ports {C0_DDR4_dq[13]}]
set_property PACKAGE_PIN AJ11 [get_ports {C0_DDR4_dq[14]}]
set_property PACKAGE_PIN AK13 [get_ports {C0_DDR4_dq[15]}]
set_property PACKAGE_PIN AF11 [get_ports {C0_DDR4_dq[16]}]
set_property PACKAGE_PIN AH9 [get_ports {C0_DDR4_dq[17]}]
set_property PACKAGE_PIN AE11 [get_ports {C0_DDR4_dq[18]}]
set_property PACKAGE_PIN AG10 [get_ports {C0_DDR4_dq[19]}]
set_property PACKAGE_PIN AF12 [get_ports {C0_DDR4_dq[20]}]
set_property PACKAGE_PIN AG11 [get_ports {C0_DDR4_dq[21]}]
set_property PACKAGE_PIN AG9 [get_ports {C0_DDR4_dq[22]}]
set_property PACKAGE_PIN AH10 [get_ports {C0_DDR4_dq[23]}]
set_property PACKAGE_PIN AN2 [get_ports {C0_DDR4_dq[24]}]
set_property PACKAGE_PIN AP7 [get_ports {C0_DDR4_dq[25]}]
set_property PACKAGE_PIN AP3 [get_ports {C0_DDR4_dq[26]}]
set_property PACKAGE_PIN AP5 [get_ports {C0_DDR4_dq[27]}]
set_property PACKAGE_PIN AM6 [get_ports {C0_DDR4_dq[28]}]
set_property PACKAGE_PIN AP6 [get_ports {C0_DDR4_dq[29]}]
set_property PACKAGE_PIN AM5 [get_ports {C0_DDR4_dq[30]}]
set_property PACKAGE_PIN AP2 [get_ports {C0_DDR4_dq[31]}]
set_property PACKAGE_PIN AM8 [get_ports {C0_DDR4_dqs_t[0]}]
set_property PACKAGE_PIN AL12 [get_ports {C0_DDR4_dqs_t[1]}]
set_property PACKAGE_PIN AJ10 [get_ports {C0_DDR4_dqs_t[2]}]
set_property PACKAGE_PIN AN5 [get_ports {C0_DDR4_dqs_t[3]}]
set_property PACKAGE_PIN AH13 [get_ports {C0_DDR4_odt[0]}]
set_property PACKAGE_PIN AK16 [get_ports C0_DDR4_act_n]
set_property PACKAGE_PIN AE16 [get_ports C0_DDR4_reset_n]

set_property PACKAGE_PIN C14 [get_ports spi_04828_clk]
set_property PACKAGE_PIN B13 [get_ports spi_04828_sdio]
set_property IOSTANDARD LVCMOS18 [get_ports spi_04828_sdio]
set_property IOSTANDARD LVCMOS18 [get_ports spi_04828_clk]
set_property IOSTANDARD LVCMOS18 [get_ports spi_04828_csn]

set_property PACKAGE_PIN E11 [get_ports pl_clk]
set_property IOSTANDARD LVCMOS33 [get_ports pl_clk]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property PACKAGE_PIN A14 [get_ports spi_04828_csn]
set_property PACKAGE_PIN E12 [get_ports {sys_clk_clk_p[0]}]
set_property IOSTANDARD LVPECL [get_ports {sys_clk_clk_p[0]}]
set_property IOSTANDARD LVPECL [get_ports {sys_clk_clk_n[0]}]




set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {u_design_1_wrapper/design_1_i/util_ds_buf_2/U0/USE_IBUFDS.GEN_IBUFDS[0].IBUFDS_I/O}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/util_ds_buf_2/U0/USE_IBUFDS.GEN_IBUFDS[0].IBUFDS_I/O]


set_property PACKAGE_PIN K10 [get_ports {ph_ctl[0]}]
set_property PACKAGE_PIN H9 [get_ports {ph_ctl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ph_ctl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ph_ctl[0]}]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PACKAGE_PIN H10 [get_ports {ph_ctl[2]}]
set_property PACKAGE_PIN G10 [get_ports {ph_ctl[3]}]
set_property PACKAGE_PIN F9 [get_ports {ph_ctl[4]}]
set_property PACKAGE_PIN F10 [get_ports {ph_ctl[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ph_ctl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ph_ctl[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ph_ctl[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ph_ctl[5]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets m_axis_ad_clk]
